### ISSUE TITLE
404 on webhook endpoint

### ISSUE THREAD

**Issue by hzik** [Kentico/kontent-boilerplate-net#92]
### Brief bug description

According to the webhook debug, new requests sometimes end up with a 404 error. The webhook endpoint is configured on ~/webhooks/webhooks. The 404 status sometimes switches to 200 after some time for already performed webhooks

### Repro steps of customer

1. Setup webhook according to https://github.com/Kentico/kontent-boilerplate-net#how-to-set-up-webhook-enabled-caching
2. Publish items
3. Watch status codes in Webhook debug in Kontent UI 

### Expected behavior

All requests return 200 unless the server is unavailable. Never get 404.

### Test environment

 - Platform/OS: .NET Core 3.1
 - Latest Boilerplate version (v4.0.2)

### Additional context

The Event log of the webhook endpoint show following stack trace:
```
System.InvalidOperationException: Unable to resolve service for type 'NoahMedia.Caching.Webhooks.ICacheManager' while attempting to activate 'NoahMedia.Areas.WebHooks.Controllers.WebhooksController'.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
at lambda_method(Closure , IServiceProvider , Object[] )
at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at NoahMedia.Middleware.SignatureMiddleware.InvokeAsync(HttpContext httpContext, IOptions`1 projectOptions) in C:\Development\Noah\noah-media-group-kentico-cloud-main-website\Middleware\SignatureMiddleware.cs:line 39
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task
```

### Conversation

All details and maybe other beneficial info can be found in conversation 26023165963 and 26078540426.

**Comment by petrsvihlik** [comment]
Hi @hzik 
the error says `Unable to resolve service for type 'NoahMedia.Caching.Webhooks.ICacheManager' while attempting to activate 'NoahMedia.Areas.WebHooks.Controllers.WebhooksController'`

This means that the implementation of the `ICacheManager` has not been registered. In the boilerplate, this is facilitated by the `AddWebhookInvalidatedCachingClient()` method called in the Startup class.

https://github.com/Kentico/kontent-boilerplate-net/blob/a8a2e001f5bb0f82a9fe7c97bd27b05a90d14899/src/content/Kentico.Kontent.Boilerplate/Caching/ServiceCollectionExtensions.cs#L31

Have you uncommented the method in the Startup class as shown below?
![image](https://user-images.githubusercontent.com/9810625/76437325-b1203900-63b9-11ea-8472-a2824df4acdc.png)
